In [ ]:
# Import necessary libraries
import urllib.request
from bs4 import BeautifulSoup
import pandas as pd

d:\PROGRAM\Anaconda\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [ ]:
# Lists of URLs for each league.  Each URL represents a team's page.
# The URLs are from the website www.transfermarkt.us

premier_league_links = ["https://www.transfermarkt.us/arsenal-fc/startseite/verein/11",
            "https://www.transfermarkt.us/aston-villa/startseite/verein/405",
            "https://www.transfermarkt.us/afc-bournemouth/startseite/verein/989",
            "https://www.transfermarkt.us/brentford-fc/startseite/verein/1148",
            "https://www.transfermarkt.us/brighton-amp-hove-albion/startseite/verein/1237",
            "https://www.transfermarkt.us/fc-chelsea/startseite/verein/631",
            "https://www.transfermarkt.us/crystal-palace/startseite/verein/873",
            "https://www.transfermarkt.us/fc-everton/startseite/verein/29",
            "https://www.transfermarkt.us/fc-fulham/startseite/verein/931",
            "https://www.transfermarkt.us/ipswich-town/startseite/verein/677",
            "https://www.transfermarkt.us/leicester-city/startseite/verein/1003",
            "https://www.transfermarkt.us/fc-liverpool/startseite/verein/31",
            "https://www.transfermarkt.us/manchester-city/startseite/verein/281",
            "https://www.transfermarkt.us/manchester-united/startseite/verein/985",
            "https://www.transfermarkt.us/newcastle-united/startseite/verein/762",
            "https://www.transfermarkt.us/nottingham-forest/startseite/verein/703",
            "https://www.transfermarkt.us/fc-southampton/startseite/verein/180",
            "https://www.transfermarkt.us/tottenham-hotspur/startseite/verein/148",
            "https://www.transfermarkt.us/west-ham-united/startseite/verein/379",
            "https://www.transfermarkt.us/wolverhampton-wanderers/startseite/verein/543"]

la_liga_links = ["https://www.transfermarkt.us/atletico-madrid/startseite/verein/13",
                "https://www.transfermarkt.us/fc-barcelona/startseite/verein/131",
                "https://www.transfermarkt.us/real-madrid/startseite/verein/418",
                "https://www.transfermarkt.us/real-betis-sevilla/startseite/verein/150",
                "https://www.transfermarkt.us/fc-sevilla/startseite/verein/368",
                "https://www.transfermarkt.us/ca-osasuna/startseite/verein/331",
                "https://www.transfermarkt.us/real-sociedad-san-sebastian/startseite/verein/681",
                "https://www.transfermarkt.us/athletic-bilbao/startseite/verein/621",
                "https://www.transfermarkt.us/deportivo-alaves/startseite/verein/1108",
                "https://www.transfermarkt.us/celta-vigo/startseite/verein/940",
                "https://www.transfermarkt.us/fc-valencia/startseite/verein/1049",
                "https://www.transfermarkt.us/fc-villarreal/startseite/verein/1050",
                "https://www.transfermarkt.us/fc-getafe/startseite/verein/3709",
                "https://www.transfermarkt.us/rayo-vallecano/startseite/verein/367",
                "https://www.transfermarkt.us/rcd-mallorca/startseite/verein/237",
                "https://www.transfermarkt.us/ud-las-palmas/startseite/verein/472",
                "https://www.transfermarkt.us/fc-girona/startseite/verein/12321",
                "https://www.transfermarkt.us/real-valladolid/startseite/verein/366",
                "https://www.transfermarkt.us/cd-leganes/startseite/verein/1244",
                "https://www.transfermarkt.us/espanyol-barcelona/startseite/verein/714"]

serie_a_links = ["https://www.transfermarkt.us/inter-milan/startseite/verein/46",
                "https://www.transfermarkt.us/ac-mailand/startseite/verein/5",
                "https://www.transfermarkt.us/juventus-turin/startseite/verein/506",
                "https://www.transfermarkt.us/atalanta-bergamo/startseite/verein/800",
                "https://www.transfermarkt.us/fc-bologna/startseite/verein/1025",
                "https://www.transfermarkt.us/as-rom/startseite/verein/12",
                "https://www.transfermarkt.us/lazio-rom/startseite/verein/398",
                "https://www.transfermarkt.us/ac-florenz/startseite/verein/430",
                "https://www.transfermarkt.us/fc-turin/startseite/verein/416",
                "https://www.transfermarkt.us/ssc-neapel/startseite/verein/6195",
                "https://www.transfermarkt.us/genua-cfc/startseite/verein/252",
                "https://www.transfermarkt.us/ac-monza/startseite/verein/2919",
                "https://www.transfermarkt.us/hellas-verona/startseite/verein/276",
                "https://www.transfermarkt.us/us-lecce/startseite/verein/1005",
                "https://www.transfermarkt.us/udinese-calcio/startseite/verein/410",
                "https://www.transfermarkt.us/cagliari-calcio/startseite/verein/1390",
                "https://www.transfermarkt.us/fc-empoli/startseite/verein/749",
                "https://www.transfermarkt.us/parma-calcio-1913/startseite/verein/130",
                "https://www.transfermarkt.us/como-1907/startseite/verein/1047",
                "https://www.transfermarkt.us/venezia-fc/startseite/verein/607"]

bundesliga_links = ["https://www.transfermarkt.us/bayer-04-leverkusen/startseite/verein/15",
                "https://www.transfermarkt.us/vfb-stuttgart/startseite/verein/79",
                "https://www.transfermarkt.us/fc-bayern-munchen/startseite/verein/27",
                "https://www.transfermarkt.us/rasenballsport-leipzig/startseite/verein/23826",
                "https://www.transfermarkt.us/borussia-dortmund/startseite/verein/16",
                "https://www.transfermarkt.us/eintracht-frankfurt/startseite/verein/24",
                "https://www.transfermarkt.us/tsg-1899-hoffenheim/startseite/verein/533",
                "https://www.transfermarkt.us/1-fc-heidenheim-1846/startseite/verein/2036",
                "https://www.transfermarkt.us/sv-werder-bremen/startseite/verein/86",
                "https://www.transfermarkt.us/sc-freiburg/startseite/verein/60",
                "https://www.transfermarkt.us/fc-augsburg/startseite/verein/167",
                "https://www.transfermarkt.us/vfl-wolfsburg/startseite/verein/82",
                "https://www.transfermarkt.us/1-fsv-mainz-05/startseite/verein/39",
                "https://www.transfermarkt.us/borussia-monchengladbach/startseite/verein/18",
                "https://www.transfermarkt.us/1-fc-union-berlin/startseite/verein/89",
                "https://www.transfermarkt.us/vfl-bochum/startseite/verein/80",
                "https://www.transfermarkt.us/fc-st-pauli/startseite/verein/35",
                "https://www.transfermarkt.us/holstein-kiel/startseite/verein/269"]

ligue_1_links = ["https://www.transfermarkt.us/fc-paris-saint-germain/startseite/verein/583",
                "https://www.transfermarkt.us/as-monaco/startseite/verein/162",
                "https://www.transfermarkt.us/stade-brest-29/startseite/verein/3911",
                "https://www.transfermarkt.us/losc-lille/startseite/verein/1082",
                "https://www.transfermarkt.us/ogc-nizza/startseite/verein/417",
                "https://www.transfermarkt.us/olympique-lyon/startseite/verein/1041",
                "https://www.transfermarkt.us/rc-lens/startseite/verein/826",
                "https://www.transfermarkt.us/olympique-marseille/startseite/verein/244",
                "https://www.transfermarkt.us/stade-reims/startseite/verein/1421",
                "https://www.transfermarkt.us/fc-stade-rennes/startseite/verein/273",
                "https://www.transfermarkt.us/fc-toulouse/startseite/verein/415",
                "https://www.transfermarkt.us/montpellier-hsc/startseite/verein/969",
                "https://www.transfermarkt.us/rc-strassburg-alsace/startseite/verein/667",
                "https://www.transfermarkt.us/fc-nantes/startseite/verein/995",
                "https://www.transfermarkt.us/ac-le-havre/startseite/verein/738",
                "https://www.transfermarkt.us/aj-auxerre/startseite/verein/290",
                "https://www.transfermarkt.us/sco-angers/startseite/verein/1420",
                "https://www.transfermarkt.us/as-saint-etienne/startseite/verein/618"]

# User agent header to mimic a browser request and avoid being blocked.
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36'}

In [4]:
for link in premier_league_links:
    start = len("https://www.transfermarkt.us/")
    end = link.find("/startseite")
    team_name = link[start:end]
    team_name = team_name.replace('-', ' ')

    print(team_name)

arsenal fc
aston villa
afc bournemouth
brentford fc
brighton amp hove albion
fc chelsea
crystal palace
fc everton
fc fulham
ipswich town
leicester city
fc liverpool
manchester city
manchester united
newcastle united
nottingham forest
fc southampton
tottenham hotspur
west ham united
wolverhampton wanderers

In [ ]:
import random

# Function to check if a string contains numbers.  Used for market value filtering.
def hasNumbers(inputString):
    return any(char.isdigit() for char in inputString)

# Main scraping function. Takes a list of team links as input.
def scrape_links(links):
    PlayersList = []
    ValuesList = []
    TeamsList = []
    

    # List of user agents to rotate, helping to avoid being blocked.
    user_agent_list = [
            # Desktop Browsers
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:120.0) Gecko/20100101 Firefox/120.0",
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_0) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15",
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",

            # Mobile Browsers
            "Mozilla/5.0 (iPhone; CPU iPhone OS 17_1_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1 Mobile/15E148 Safari/604.1",
            "Mozilla/5.0 (Linux; Android 14; Pixel 8 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36",
            "Mozilla/5.0 (Linux; Android 13; SAMSUNG SM-G991B) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/23.0 Chrome/116.0.0.0 Mobile Safari/537.36",
            "Mozilla/5.0 (iPad; CPU OS 17_1_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1",

            # Search Bots
            "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)",
             "Mozilla/5.0 (compatible; Bingbot/2.0; +http://www.bing.com/bingbot.htm)"
    ]
    
    for link in links:
        team_players = []
        team_values = []
        
        # Extract team name from the URL.        
        start = len("https://www.transfermarkt.us/")
        end = link.find("/startseite")
        team_name = link[start:end]
        team_name = team_name.replace('-', ' ')

        # Randomly select a user agent for this request.
        user_agent = random.choice(user_agent_list)
        headers = {'User-Agent': user_agent}

        # Make the HTTP request to the URL.
        req = urllib.request.Request(url=link, headers=headers)
        with urllib.request.urlopen(req) as response:
            page_html = response.read()

        # Parse the HTML using BeautifulSoup.
        soup = BeautifulSoup(page_html, 'html.parser')
       

        # Extract player names from the table. This section uses a more robust method
        # to find player names compared to the commented-out code.
        inline_tables = soup.find_all("table", {"class": "inline-table"})

        # Extract market values. Handles cases where value is missing ('0').
        for table in inline_tables:
            player_link = table.find("a")
            if player_link:
                player_name = player_link.text.strip()
                if player_name not in team_players:
                    team_players.append(player_name)
                    PlayersList.append(player_name)
                    TeamsList.append(team_name)

        values = soup.find_all("td", {"class": "rechts hauptlink"})
        for i in range(len(values)):
            value = values[i].text
            if hasNumbers(value) == True:
                ValuesList.append(value)
                team_values.append(value)

            else:
                ValuesList.append('0')
                team_values.append('0')

        print("num players: ", len(team_players), "  num values: ", len(team_values))
        
                
    print(len(PlayersList))
    print(len(ValuesList))

    # Create a Pandas DataFrame from the collected data.
    df = pd.DataFrame({'Players': PlayersList, "Values": ValuesList, "Team": TeamsList})
    return df

In [ ]:
# Scrape data for each league and save to a CSV file.
premier_league_df = scrape_links(premier_league_links)

num players:  24   num values:  24
num players:  25   num values:  25
num players:  25   num values:  25
num players:  28   num values:  28
num players:  27   num values:  27
num players:  33   num values:  33
num players:  30   num values:  30
num players:  25   num values:  25
num players:  25   num values:  25
num players:  31   num values:  31
num players:  31   num values:  31
num players:  25   num values:  25
num players:  28   num values:  28
num players:  29   num values:  29
num players:  29   num values:  29
num players:  28   num values:  28
num players:  32   num values:  32
num players:  30   num values:  30
num players:  24   num values:  24
num players:  32   num values:  32
561
561

In [16]:
premier_league_df

                  Players   Values                     Team
0              David Raya  €40.00m               arsenal fc
1                    Neto   €2.00m               arsenal fc
2          William Saliba  €80.00m               arsenal fc
3       Gabriel Magalhães  €75.00m               arsenal fc
4            Jakub Kiwior  €28.00m               arsenal fc
..                    ...      ...                      ...
556         Matheus Cunha  €50.00m  wolverhampton wanderers
557  Jørgen Strand Larsen  €27.00m  wolverhampton wanderers
558        Hee-chan Hwang  €22.00m  wolverhampton wanderers
559        Sasa Kalajdzic   €5.00m  wolverhampton wanderers
560         Nathan Fraser    €600k  wolverhampton wanderers

[561 rows x 3 columns]

In [19]:
la_liga_df = scrape_links(la_liga_links)

num players:  24   num values:  24
num players:  28   num values:  28
num players:  23   num values:  23
num players:  25   num values:  25
num players:  25   num values:  25
num players:  22   num values:  22
num players:  25   num values:  25
num players:  24   num values:  24
num players:  24   num values:  24
num players:  27   num values:  27
num players:  28   num values:  28
num players:  26   num values:  26
num players:  24   num values:  24
num players:  25   num values:  25
num players:  26   num values:  26
num players:  27   num values:  27
num players:  26   num values:  26
num players:  23   num values:  23
num players:  23   num values:  23
num players:  30   num values:  30
505
505

In [20]:
la_liga_df

                Players   Values                Team
0             Jan Oblak  €25.00m     atletico madrid
1            Juan Musso   €4.00m     atletico madrid
2      Robin Le Normand  €40.00m     atletico madrid
3    José María Giménez  €20.00m     atletico madrid
4       Clément Lenglet   €7.50m     atletico madrid
..                  ...      ...                 ...
500         Alejo Veliz   €4.00m  espanyol barcelona
501      Walid Cheddira   €4.00m  espanyol barcelona
502   Roberto Fernández   €3.50m  espanyol barcelona
503       Irvin Cardona   €2.00m  espanyol barcelona
504          Omar Sadik    €300k  espanyol barcelona

[505 rows x 3 columns]

In [21]:
bundesliga_df = scrape_links(bundesliga_links)

num players:  25   num values:  25
num players:  34   num values:  34
num players:  26   num values:  26
num players:  26   num values:  26
num players:  25   num values:  25
num players:  25   num values:  25
num players:  31   num values:  31
num players:  28   num values:  28
num players:  26   num values:  26
num players:  26   num values:  26
num players:  28   num values:  28
num players:  30   num values:  30
num players:  25   num values:  25
num players:  25   num values:  25
num players:  29   num values:  29
num players:  27   num values:  27
num players:  33   num values:  33
num players:  30   num values:  30
499
499

In [22]:
bundesliga_df

                    Players   Values                 Team
0               Matej Kovar   €7.00m  bayer 04 leverkusen
1            Lukas Hradecky   €2.00m  bayer 04 leverkusen
2               Niklas Lomb    €250k  bayer 04 leverkusen
3           Luca Novodomsky        0  bayer 04 leverkusen
4            Piero Hincapié  €40.00m  bayer 04 leverkusen
..                      ...      ...                  ...
494  Alexander Bernhardsson   €1.50m        holstein kiel
495           Shuto Machino   €3.00m        holstein kiel
496        Benedikt Pichler   €2.00m        holstein kiel
497             Phil Harres   €1.50m        holstein kiel
498               Fiete Arp    €800k        holstein kiel

[499 rows x 3 columns]

In [23]:
ligue_1_df = scrape_links(ligue_1_links)

num players:  24   num values:  24
num players:  25   num values:  25
num players:  25   num values:  25
num players:  26   num values:  26
num players:  29   num values:  29
num players:  24   num values:  24
num players:  27   num values:  27
num players:  30   num values:  30
num players:  25   num values:  25
num players:  25   num values:  25
num players:  23   num values:  23
num players:  27   num values:  27
num players:  29   num values:  29
num players:  26   num values:  26
num players:  30   num values:  30
num players:  28   num values:  28
num players:  30   num values:  30
num players:  27   num values:  27
480
480

In [24]:
ligue_1_df

                  Players   Values                    Team
0    Gianluigi Donnarumma  €35.00m  fc paris saint germain
1          Matvey Safonov  €22.00m  fc paris saint germain
2             Arnau Tenas   €4.00m  fc paris saint germain
3              Marquinhos  €40.00m  fc paris saint germain
4           Willian Pacho  €40.00m  fc paris saint germain
..                    ...      ...                     ...
475   Zuriko Davitashvili   €8.00m        as saint etienne
476        Mathieu Cafaro   €2.00m        as saint etienne
477         Lucas Stassin   €5.00m        as saint etienne
478       Ibrahim Sissoko   €2.50m        as saint etienne
479        Ibrahima Wadji    €800k        as saint etienne

[480 rows x 3 columns]

In [25]:
serie_a_df = scrape_links(serie_a_links)

num players:  26   num values:  26
num players:  26   num values:  26
num players:  28   num values:  28
num players:  25   num values:  25
num players:  29   num values:  29
num players:  25   num values:  25
num players:  30   num values:  30
num players:  26   num values:  26
num players:  28   num values:  28
num players:  24   num values:  24
num players:  32   num values:  32
num players:  30   num values:  30
num players:  32   num values:  32
num players:  34   num values:  34
num players:  34   num values:  34
num players:  24   num values:  24
num players:  27   num values:  27
num players:  32   num values:  32
num players:  36   num values:  36
num players:  29   num values:  29
577
577

In [26]:
serie_a_df

                    Players   Values         Team
0            Josep Martínez  €12.00m  inter milan
1               Yann Sommer   €4.00m  inter milan
2               Andrei Radu   €1.50m  inter milan
3       Raffaele Di Gennaro    €300k  inter milan
4        Alessandro Bastoni  €75.00m  inter milan
..                      ...      ...          ...
572          Alessio Zerbin   €3.50m   venezia fc
573        Bjarki Bjarkason    €800k   venezia fc
574         Joel Pohjanpalo   €5.00m   venezia fc
575      Christian Gytkjaer    €700k   venezia fc
576  Hilmir Rafn Mikaelsson    €600k   venezia fc

[577 rows x 3 columns]

In [27]:
premier_league_df.to_csv('premier_league_market_value.csv')
la_liga_df.to_csv('la_liga_market_value.csv')
bundesliga_df.to_csv('bundesliga_market_value.csv')
ligue_1_df.to_csv('ligue_1_market_value.csv')
serie_a_df.to_csv('serie_a_market_value.csv')